/*
 * Created on 2017-03-22 ( Date ISO 2017-03-22 - Time 23:34:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.jsonmapper;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import org.demo.bean.MyBeanSqlDate;
import org.demo.jsonmapper.JsonMapper;
import org.demo.jsonmapper.impl.gson.GsonMapper;
import org.demo.jsonmapper.impl.jackson.JacksonMapper;
import org.junit.Test;

/**
 * JUnit tests for DriverRecord persistence service
 * 
 * @author Telosys
 *
 */
public class MyBeanSqlDateJsonTest {

	private JsonMapper<MyBeanSqlDate> getGsonMapper() {
		return new GsonMapper<MyBeanSqlDate>(MyBeanSqlDate.class);
	}
	private JsonMapper<MyBeanSqlDate> getJacksonMapper() {
		return new JacksonMapper<MyBeanSqlDate>(MyBeanSqlDate.class);
	}

	//----- JACKSON
	@Test
	public void testJacksonSqlDate() {
		testConvert(getJacksonMapper(), java.sql.Date.valueOf("2001-06-22") );
	}	
	@Test
	public void testJacksonSqlDate2() {
		java.util.Date now = new java.util.Date();
		testConvert(getJacksonMapper(), new java.sql.Date(now.getTime()));
	}	

	//----- GSON
	@Test
	public void testGsonSqlDate() {
		testConvert(getGsonMapper(), java.sql.Date.valueOf("2001-06-22"));
	}	
	@Test
	public void testGsonSqlDate2() {
		java.util.Date now = new java.util.Date();
		testConvert(getGsonMapper(), new java.sql.Date(now.getTime()));
	}	

	private void testConvert(JsonMapper<MyBeanSqlDate> m, java.sql.Date date) {
		
		System.out.println("-------------------------------------------");
		System.out.println("Mapper : " + m.getClass().getSimpleName() );
		System.out.println("Given date : " + date.getClass().getCanonicalName() + " : '" + date + "' ( " + date.getTime() + " )");
		MyBeanSqlDate bean1 = new MyBeanSqlDate();
		bean1.setId((short)1); // "id" : short
		bean1.setBirthDate(date); // "birthDate" : java.util.Date

    	System.out.println("Instance 1 : " + bean1 );

		String json = m.beanToJson(bean1);
    	System.out.println(json );
		
    	MyBeanSqlDate bean2 = m.jsonToBean(json);
    	System.out.println("Instance 2 : " + bean2 );

		assertNotNull(bean2);
		
		System.out.println("driver1 : birthDate = " + bean1.getBirthDate() );
		System.out.println("driver2 : birthDate = " + bean2.getBirthDate() );

		assertEquals(bean1.getBirthDate(), bean2.getBirthDate() ); 
		assertTrue( bean1.getBirthDate().compareTo(bean2.getBirthDate()) == 0 ); 
		assertTrue( bean1.getBirthDate().equals(bean2.getBirthDate()) ); 
		
	}	
}
