/*
 * Created on 2017-03-22 ( Date ISO 2017-03-22 - Time 23:34:18 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.jsonmapper;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import org.demo.bean.MyBeanSqlTime;
import org.demo.jsonmapper.JsonMapper;
import org.demo.jsonmapper.impl.gson.GsonMapper;
import org.demo.jsonmapper.impl.jackson.JacksonMapper;
import org.junit.Test;

/**
 * JUnit tests for DriverRecord persistence service
 * 
 * @author Telosys
 *
 */
public class MyBeanSqlTimeJsonTest {

	private JsonMapper<MyBeanSqlTime> getGsonMapper() {
		return new GsonMapper<MyBeanSqlTime>(MyBeanSqlTime.class);
	}
	private JsonMapper<MyBeanSqlTime> getJacksonMapper() {
		return new JacksonMapper<MyBeanSqlTime>(MyBeanSqlTime.class);
	}

	//----- JACKSON
	@Test
	public void testJacksonSqlTime() {
		testConvert(getJacksonMapper(), java.sql.Time.valueOf("12:34:56") );
	}	
	@Test
	public void testJacksonSqlTime2() {
		java.util.Date now = new java.util.Date();
		testConvert(getJacksonMapper(), new java.sql.Time(now.getTime()));
	}	

	//----- GSON
	@Test
	public void testGsonSqlTime() {
		testConvert(getGsonMapper(), java.sql.Time.valueOf("12:34:56"));
	}	
	@Test
	public void testGsonSqlTime2() {
		java.util.Date now = new java.util.Date();
		testConvert(getGsonMapper(), new java.sql.Time(now.getTime()));
	}	
	@Test
	public void testGsonSqlTimeNull() {
		testConvert(getGsonMapper(), null);
	}	

	private void testConvert(JsonMapper<MyBeanSqlTime> m, java.sql.Time time) {
		
		System.out.println("-------------------------------------------");
		System.out.println("Mapper : " + m.getClass().getSimpleName() );
		if ( time != null ) {
			System.out.println("Given  : " + time.getClass().getCanonicalName() + " : '" + time + "' ( " + time.getTime() + " )");
		}
		MyBeanSqlTime bean1 = new MyBeanSqlTime();
		bean1.setId((short)1); // "id" : short
		bean1.setTime(time); // "birthDate" : java.util.Date

    	System.out.println("Instance 1 : " + bean1 );

		String json = m.beanToJson(bean1);
    	System.out.println(json );
		
    	MyBeanSqlTime bean2 = m.jsonToBean(json);
    	System.out.println("Instance 2 : " + bean2 );

		assertNotNull(bean2);
		
		assertEquals(bean1.getTime(), bean2.getTime() ); 
		if ( bean1.getTime() != null ) {
			assertTrue( bean1.getTime().compareTo(bean2.getTime()) == 0 ); 
			assertTrue( bean1.getTime().equals(bean2.getTime()) );
		}
    	System.out.println("Test OK");
	}	
}
