/*
 * Created on 2017-04-24 ( Date ISO 2017-04-24 - Time 18:41:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package org.demo.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Java bean for entity "Driver" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class MyBeanUtilDate implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Short id ; // short // Id or Primary Key

    private Date birthDate ;  // date -> Date 
    
    /**
     * Default constructor
     */
    public MyBeanUtilDate() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "", NotNull : true ) 
     * @param id
     */
	public void setId( Short id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "", NotNull : true ) 
     * @return the field value
     */
	public Short getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "birthDate" field value
     * This field is mapped on the database column "birthDate" ( type "", NotNull : false ) 
     * @param birthDate
     */
    public void setBirthDate( Date birthDate ) {
        this.birthDate = birthDate;
    }
    /**
     * Get the "birthDate" field value
     * This field is mapped on the database column "birthDate" ( type "", NotNull : false ) 
     * @return the field value
     */
    public Date getBirthDate() {
        return this.birthDate;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(birthDate);
        return sb.toString(); 
    } 



}
