/*
 * Created on 2017-04-24 ( Date ISO 2017-04-24 - Time 18:41:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package org.demo.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Java bean for entity "Driver" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class MyBean implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Short id ; // short // Id or Primary Key


    private String firstName ;  // string -> String 

    private String lastName ;  // string -> String 

    private Date birthDate ;  // date -> Date 
    
    private java.sql.Date sqlDate ; 
    private java.sql.Time sqlTime ; 
    private java.sql.Timestamp sqlTimestamp ; 

	/**
     * Default constructor
     */
    public MyBean() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "", NotNull : true ) 
     * @param id
     */
	public void setId( Short id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "", NotNull : true ) 
     * @return the field value
     */
	public Short getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "firstName" field value
     * This field is mapped on the database column "firstName" ( type "", NotNull : false ) 
     * @param firstName
     */
    public void setFirstName( String firstName ) {
        this.firstName = firstName;
    }
    /**
     * Get the "firstName" field value
     * This field is mapped on the database column "firstName" ( type "", NotNull : false ) 
     * @return the field value
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Set the "lastName" field value
     * This field is mapped on the database column "lastName" ( type "", NotNull : false ) 
     * @param lastName
     */
    public void setLastName( String lastName ) {
        this.lastName = lastName;
    }
    /**
     * Get the "lastName" field value
     * This field is mapped on the database column "lastName" ( type "", NotNull : false ) 
     * @return the field value
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Set the "birthDate" field value
     * This field is mapped on the database column "birthDate" ( type "", NotNull : false ) 
     * @param birthDate
     */
    public void setBirthDate( Date birthDate ) {
        this.birthDate = birthDate;
    }
    /**
     * Get the "birthDate" field value
     * This field is mapped on the database column "birthDate" ( type "", NotNull : false ) 
     * @return the field value
     */
    public Date getBirthDate() {
        return this.birthDate;
    }

    public java.sql.Date getSqlDate() {
		return sqlDate;
	}

	public void setSqlDate(java.sql.Date sqlDate) {
		this.sqlDate = sqlDate;
	}

	public java.sql.Time getSqlTime() {
		return sqlTime;
	}

	public void setSqlTime(java.sql.Time sqlTime) {
		this.sqlTime = sqlTime;
	}

	public java.sql.Timestamp getSqlTimestamp() {
		return sqlTimestamp;
	}

	public void setSqlTimestamp(java.sql.Timestamp sqlTimestamp) {
		this.sqlTimestamp = sqlTimestamp;
	}

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(lastName);
        sb.append("|");
        sb.append(birthDate);
        sb.append("|");
        sb.append(sqlDate);
        sb.append("|");
        sb.append(sqlTime);
        sb.append("|");
        sb.append(sqlTimestamp);
        return sb.toString(); 
    } 



}
